# New ports collection makefile for:	trueos-meta-mysql
#
# $FreeBSD$
#

PORTNAME=	trueos-meta-mysql
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port trueos-meta-mysql

RUN_DEPENDS=	mysql-server>=0:${PORTSDIR}/databases/mysql55-server

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
