#############################################################################
# Makefile for building: xtrafiles
#############################################################################

PREFIX?= /usr/local

####### Install

all:

install_doinstall:
	sh install.sh $(INSTALL_ROOT)$(PREFIX)

install:  install_doinstall
