DE_NAME="Gnome"
XDG="NO"

DE_SESSION_NAME="GNOME"
DE_METAPACKAGE="KDE"
DE_INSTALL_FILE="gnome-session"

DE_SU="gksu %s"
DE_FILEMAN="nautilus %s"
DE_TERMINAL="gnome-terminal"
DE_TERMINAL_TITLE="-t"
DE_TERMINAL_COMMAND="-e"

