DE_NAME="KDE"
XDG="YES"

DE_SESSION_NAME="KDE"
DE_METAPACKAGE="KDE"
DE_INSTALL_FILE="_startkde4  _startkde"

DE_SU="kdesu %s"
DE_TERMINAL="konsole"
DE_TERMINAL_TITLE="--caption"
DE_TERMINAL_COMMAND="-e"
DE_TERMINAL_SEPARATE_ARGS="YES"
DE_FILEMAN="dolphin %s"

