#!/bin/sh
DE_NAME="LXDE"
XDG="YES"

DE_SESSION_NAME="LXDE"
DE_METAPACKAGE="LXDE"
DE_INSTALL_FILE="startlxde"

DE_FILEMAN="pcmanfm %s"
DE_TERMINAL="lxterminal"
DE_TERMINAL_TITLE="-T"
DE_TERMINAL_COMMAND="-e"

