#!/bin/sh
DE_NAME="XFCE"

DE_SESSION_NAME="XFCE"
DE_METAPACKAGE="XFCE"
DE_INSTALL_FILE="startxfce4 startxfce"

XDG="YES"
DE_SU="pc-su %s"
DE_FILEMAN="thunar %s"
DE_TERMINAL="xfce4-terminal"
DE_TERMINAL_TITLE="-T"
DE_TERMINAL_COMMAND="-e"
