#!/bin/sh

# PROVIDE: hwdetect
# REQUIRE: DAEMON
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="hwdetect"
rcvar=hwdetect_enable

stop_cmd="hwdetect_stop"
start_cmd="hwdetect_start"

load_rc_config $name

: ${hwdetect_enable=NO}

hwdetect_start()
{
	/usr/local/bin/pc-hwdetect
}

hwdetect_stop()
{
	echo ""
}

run_rc_command "$1"

