#!/bin/sh

# PROVIDE: pcbsdinit
# REQUIRE: DAEMON cups
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="pcbsdinit"
rcvar=pcbsdinit_enable

stop_cmd="pcbsdinit_stop"
start_cmd="pcbsdinit_start"

load_rc_config $name

: ${pcbsdinit_enable=NO}

pcbsdinit_start()
{
	echo "Starting PC-BSD init.."
	if [ -e "/var/.pcbsd-firstboot" ] ; then
		(/usr/local/share/pcbsd/scripts/first-boot.sh >/dev/null 2>/dev/null ; rm /var/.pcbsd-firstboot)&
	fi

	# Cleanup cups print jobs
	/usr/local/bin/cancel -a 2>/dev/null >/dev/null

	# Change Xorg priority
	( sleep 40; rtprio 31 -`pgrep Xorg` 2>/dev/null)&

	# Check for any new wifi devices to setup
	for wnic in `sysctl -b net.wlan.devices 2>/dev/null`
	do
		cat ${FSMNT}/etc/rc.conf 2>/dev/null | grep -q "wlans_${wnic}="
		if [ $? -ne 0 ] ; then
			# We have a wifi device, setup a wlan* entry for it
			grep -q "^wlans_" /etc/rc.conf
			if [ $? -eq 0 ] ; then
				WLANCOUNT=`cat /etc/rc.conf | grep "^wlans_" | wc -l | awk '{print $1}'`
			else
				WLANCOUNT="0"
			fi
			WLAN="wlan${WLANCOUNT}"

			# Save the wlan interface
			echo "wlans_${wnic}=\"${WLAN}\"" >>${FSMNT}/etc/rc.conf

			# Create the wlanX device
			ifconfig $WLAN create wlandev $wnic
		fi
	done

}

pcbsdinit_stop()
{
}

run_rc_command "$1"
