#!/bin/sh

# PROVIDE: warden
# REQUIRE: DAEMON
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="warden"
rcvar="warden_enable"

stop_cmd="warden_stop"
start_cmd="warden_start"

load_rc_config $name

: ${warden_enable=NO}

warden_start()
{

  # Make sure we have a conf file
  if [ ! -e "/usr/local/etc/warden.conf" ]; then
     cp /usr/local/etc/warden.conf.dist /usr/local/etc/warden.conf
  fi

  PROGDIR="/usr/local/share/warden"
  $PROGDIR/scripts/rc.d/startup.sh
}

warden_stop()
{
  PROGDIR="/usr/local/share/warden"
  $PROGDIR/scripts/rc.d/shutdown.sh
}

run_rc_command "$1"

