PREFIX?= /usr/local
FILES=pc-activedirectory pc-kerberos pc-kinit pc-nsswitch pc-pam \
	pc-samba pc-ldap pc-nssldap pc-directory

FILESMODE=0555
FILESDIR=$(PREFIX)/etc/rc.d
NO_OBJ=

.include <bsd.prog.mk>
