#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: pc_kinit
# REQUIRE: kerberos
# REQUIRE: pc_samba
# REQUIRE: ntpd

. /etc/rc.conf
. /usr/local/etc/rc.activedirectory

pc_kinit_enable=${pc_activedirectory_enable-"NO"}

name="pc_kinit"
rcvar="pc_kinit_enable"

kinit_start()
{
	local re=1
	local pwfile

	AD_init

	local domainname=$(AD_get domainname)
	local adminname=$(AD_get adminname)
	local adminpw=$(AD_get adminpw)

	if [ -n "${adminname}" -a -n "${domainname}" -a -n "${adminpw}" ]
	then
		domainname=$(echo "${domainname}" | tr a-z A-Z)

		pwfile=$(mktemp /tmp/tmp.XXXXXXXX)
		printf "${adminpw}" > ${pwfile}

		AD_log "kinit_start: kinit --password-file=${pwfile} " \
		    "${adminname}@${domainname}"
		kinit --password-file="${pwfile}" \
		    "${adminname}@${domainname}"
		res=$?

		local ok="Failed"
		if [ "${res}" = "0" ]
		then
			ok="Successful"
		fi

		AD_log "kinit_start: ${ok}"
		rm -f "${pwfile}"
		sleep 10
	fi

	return ${res}
}

kinit_status()
{
	local res=1

	AD_init

	local domainname=$(AD_get domainname)
	local adminname=$(AD_get adminname)
	local adminpw=$(AD_get adminpw)

	if [ -n "${adminname}" -a -n "${domainname}" -a -n "${adminpw}" ]
	then
		domainname=$(echo "${domainname}"|tr a-z A-Z)

		AD_log "kinit_status: klist -l | grep -q ^${adminname}@${domainname}"
		klist -l | grep -q "^${adminname}@${domainname}"
		res=$?

		local ok="Failed"
		if [ "${res}" = "0" ]
		then
			ok="Successful"
		fi

		AD_log "kinit_status: ${ok}"
	fi

	return ${res}
}

kinit_stop()
{
	AD_log "kinit_stop: kdestroy"

	kdestroy
	local ok="Failed"
	if [ "${res}" = "0" ]
	then
		ok="Successful"
	fi

	AD_log "kinit_stop: ${ok}"
	return 0
}

extra_commands="status"
start_cmd='kinit_start'
status_cmd='kinit_status'
stop_cmd='kinit_stop'

load_rc_config $name
run_rc_command "$1"
