#############################################################################
# Makefile for building: lpreserver
#############################################################################

####### Install

all:

install_doinstall:
	sh install.sh

install:  install_doinstall
