# New ports collection makefile for:	pcbsd-meta-handheld
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-handheld
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-handheld

RUN_DEPENDS=	synce-librapi2>=0:${PORTSDIR}/palm/synce-librapi2 \
		synce-librra>=0:${PORTSDIR}/palm/synce-librra

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
