# New ports collection makefile for:	pkgdemon-meta-gnome3
#
# $FreeBSD$
#

PORTNAME=	pkgdemon-meta-gnome3
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pkgdemon-meta-gnome3

RUN_DEPENDS=	gnome3>=0:${PORTSDIR}/x11/gnome3

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
