#!/bin/sh
#Set cross-application notification flags

manpage(){
echo "USAGE: pc-systemflag <FLAG> <MESSAGE>
	FLAGS:
	PBIUPDATE  - PBI Update Availability Changed
	PKGUPDATE  - pkg Update Availability Changed
	SYSUPDATE  - System Update Availability Changed
	NETRESTART - Network Access Changed

	MESSAGES:
	WORKING	-  App is currently working
	ERROR	-  App experienced an error
	SUCCESS	-  App finished successfully
	UPDATE	-  App has updates available
	
EXAMPLE 1: pc-systemflag PBIUPDATE UPDATE (A PBI can be updated)
EXAMPLE 2: pc-systemflag NETRESTART SUCCESS (Network restarted successfully)
EXAMPLE 3: pc-systemflag SYSUPDATE ERROR (Could not check for system updates)
"
exit 1
}

#Check for help pages
if [ ${1} = "-h" -o ${1} = "help" ]; then
 manpage
elif [ ! -n "${1}" ]; then
 manpage
fi

#echo "${1} + ${2}"

#Always check for the existance of the flag directory and try to create it if possible
FLAGDIR="/tmp/.pcbsdflags"
if [ ! -d ${FLAGDIR} ]; then
  mkdir -p -m 777 ${FLAGDIR}
fi

#Figure out which flag type this is for
if [ ${1} = "PBIUPDATE" ]; then
  FLAGFILE="${FLAGDIR}/pbi-update-available-${LOGNAME}"
elif [ ${1} = "PKGUPDATE" ]; then
  FLAGFILE="${FLAGDIR}/pkg-update-available-${LOGNAME}"
elif [ ${1} = "SYSUPDATE" ]; then
  FLAGFILE="${FLAGDIR}/sys-update-available-${LOGNAME}"
elif [ ${1} = "NETRESTART" ]; then
  FLAGFILE="${FLAGDIR}/network-restarted-${LOGNAME}"
elif [ ${1} = "CHECKDIR" ]; then
  exit 0
else
  echo "Invalid Option: ${1}"
  manpage
fi

#Figure out which flag message this is
if [ ${2} = "WORKING" ]; then
  MSG="working"
elif [ ${2} = "ERROR" ]; then
  MSG="error"
elif [ ${2} = "SUCCESS" ]; then
  MSG="success"
elif [ ${2} = "UPDATE" ]; then
  MSG="updateavailable"
else
  echo "Invalid Message: ${2}"
  manpage
fi
#Set the flag
echo ${MSG} > ${FLAGFILE}
exit 0