# New ports collection makefile for:	pcbsd-meta-compiz
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-compiz
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-compiz

RUN_DEPENDS=	compiz-fusion>=0:${PORTSDIR}/x11-wm/compiz-fusion

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
