# New ports collection makefile for:	pcbsd-meta-kde-pim
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-kde-pim
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-kde-pim

RUN_DEPENDS=	kdepim>=0:${PORTSDIR}/deskutils/kdepim4 \
		akonadi-googledata>=0:${PORTSDIR}/databases/akonadi-googledata

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
