# New ports collection makefile for:	trueos-meta-apache
#
# $FreeBSD$
#

PORTNAME=	trueos-meta-apache
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port trueos-meta-apache

RUN_DEPENDS=	apache22>=0:${PORTSDIR}/www/apache22

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
