# New ports collection makefile for:	pcbsd-role-plex
#
# $FreeBSD$
#

PORTNAME=	pcbsd-role-plex
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	joshms@pcbsd.org
COMMENT=	Includes software for the plex role

RUN_DEPENDS=	plex>=0:${PORTSDIR}/multimedia/plexhometheater

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
