# New ports collection makefile for:	trueos-meta-samba
#
# $FreeBSD$
#

PORTNAME=	trueos-meta-samba
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port trueos-meta-samba

RUN_DEPENDS=	samba41>=0:${PORTSDIR}/net/samba41

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
