# New ports collection makefile for:	pcbsd-meta-kde-education
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-kde-education
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-kde-education

RUN_DEPENDS=	kdeedu>=0:${PORTSDIR}/misc/kdeedu4

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
