#!/bin/sh
#
# Copyright 2013 iXsystems (Kris Moore)
# All rights reserved
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted providing that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Script to detect other NON BSD OS's and add to grub.cfg

check_ntfs_part()
{
   if [ "$3" = "MBR" ] ; then
     cDisk="${1}s${2}" 
   else
     cDisk="${1}p${2}" 
   fi
   # Check the partition for a boot sector
   glabel status ${cDisk} 2>/dev/null | grep -q "System Reserved"
   if [ $? -ne 0 ] ; then return ; fi
   cat << EOF
menuentry "Microsoft Windows ($cDisk)" {
   insmod ntfs
   set root(hd${dNum},$2)
   chainloader +1
}
EOF
}

dFile="/tmp/.disk-probe.$$"
dNum="0"

# Start by looking for disks
for disk in `cd /dev/ && ls ada[0-9] da[0-9] 2>/dev/null`
do
   if [ -e "$dFile" ] ; then rm $dFile; fi
   gpart show $disk 2>/dev/null >${dFile}
   pType=""
   while read dLine
   do
     echo "$dLine" | grep -q '=>' 
     if [ $? -eq 0 ] ; then
        pType=`echo $dLine | awk '{print $5}'`
        continue
     fi
     fsType=`echo $dLine | awk '{print $4}'`
     fsPart=`echo $dLine | awk '{print $3}'`
     case $fsType in
          ntfs) check_ntfs_part "$disk" "$fsPart" "$pType" ;;
             *) ;; # Unknown / unsupported FS - Add more here!
     esac

   done < $dFile

   # Increment our disk counter
   dNum="`expr $dNum + 1`"
done

rm $dFile
