# New ports collection makefile for:	pcbsd-meta-gnome-games
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-gnome-games
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-gnome-games

RUN_DEPENDS=	gnome-games>=0:${PORTSDIR}/games/gnome-games \
		gnome-games-extra-data>=0:${PORTSDIR}/games/gnome-games-extra-data

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
