.Dd Apr 15, 2010
.Dt PBI_ADD 1
.Os
.Sh NAME
.Nm pbi_add
.Nd Install a PBI file
.Sh SYNOPSIS
.Nm
.Op Fl f
.Op Fl i
.Op Fl j
.Op Fl J
.Op Fl l
.Op Fl v
.Op Ar pbi
.Sh DESCRIPTION
The utility,
.Nm ,
installs, extracts or displays information from a pbi file 
packaged with pbi_create. 
.Sh WARNING
The pbi_add command may execute scripts or programs contained
within a PBI file. Your system may be susceptible to 'trojan horses'
or other subtle attacks from malicious developers who create dangerous
pbi files.

You are advised to verify the competence and identify of those who provide
PBI files. For extract protection, use the -e and --checkscript options 
to view archive contents and installation scripts prior to installing
a PBI file. 
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Fl f
Force installation, overwriting an already installed copy of the application
.It Fl i
Display information about this PBI file
.It Fl l
Display LICENSE information for this PBI file.
.It Fl j Ar jail
Install target PBI into jail <jail>
.It Fl J
Create a new jail automatically via Warden, and install PBI into it
.It Fl v
Enable verbose output
.Sh NOTES
For details about the module format, please refer to the wiki guide:
http://wiki.pcbsd.org/index.php/PBI_Module_Builder_Guide
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_delete 1 ,
.Xr pbi_info 1
