######################################################################
# Automatically generated by qmake (1.07a) Mon Jan 1 20:42:56 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += rcconfig.hpp
SOURCES += rcconfig.cpp
