# New ports collection makefile for:	pcbsd-meta-cinnamon
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-cinnamon
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-cinnamon

RUN_DEPENDS=	cinnamon>=0:${PORTSDIR}/x11/cinnamon

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
