# New ports collection makefile for:	trueos-meta-squid
#
# $FreeBSD$
#

PORTNAME=	trueos-meta-squid
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port trueos-meta-squid

RUN_DEPENDS=	squid>=0:${PORTSDIR}/www/squid32

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
