# New ports collection makefile for:	trueos-meta-virtualbox
#
# $FreeBSD$
#

PORTNAME=	trueos-meta-virtualbox
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port trueos-meta-virtualbox

RUN_DEPENDS=	virtualbox-ose>=0:${PORTSDIR}/emulators/virtualbox-ose \
		phpvirtualbox>=0:${PORTSDIR}/www/phpvirtualbox

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
