# New ports collection makefile for:	pcbsd-meta-kde-l10n
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-kde-l10n
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-kde-l10n

RUN_DEPENDS=	kde-l10n>=0:${PORTSDIR}/misc/kde4-l10n

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
