#!/bin/sh
# $FreeBSD$

# PROVIDE: syscache
# REQUIRE: LOGIN cleanvar
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable syscache:
# syscache_enable (bool):		Set to "NO" by default.
#				Set it to "YES" to enable syscache 

. /etc/rc.subr

name="syscache"
rcvar=syscache_enable

command="/usr/local/bin/syscache-daemon"
command2="/usr/local/bin/syscache-webclient"
start_cmd="syscache_start"
stop_cmd="syscache_stop"

[ -z "$syscache_enable" ]		&& syscache_enable="NO"

load_rc_config $name

syscache_stop()
{
  if [ -e "/var/run/syscache.pid" ] ; then
    pkill -9 -F /var/run/syscache.pid
  fi
  if [ -e "/var/run/syscache-websocket.pid" ] ; then
    pkill -9 -F /var/run/syscache-websocket.pid
  fi
}

syscache_start()
{
  export PATH="${PATH}:/usr/local/bin:/usr/local/sbin"
  syscache_stop
  echo "Starting syscache..."
  if [ -e "/var/run/syscache.pipe" ] ; then
    rm /var/run/syscache.pipe >/dev/null 2>/dev/null
  fi
  # Make sure the working file exists
  if [ ! -d "/var/tmp/appcafe" ] ; then
    mkdir -p /var/tmp/appcafe
  fi
  touch /var/tmp/appcafe/dispatcher-queue.working

  # If not on PC-BSD
  if [ ! -e "/etc/defaults/pcbsd" ] ; then
    flags="-sync-now"
  else
    flags=""
  fi

  daemon -p /var/run/syscache.pid $command $flags >/dev/null 2>/dev/null
  daemon -p /var/run/syscache-websocket.pid $command2 >/dev/null 2>/dev/null
}

run_rc_command "$1"
