#!/bin/sh
#
# Copyright 2014 Kris Moore (iXsystems)
# All rights reserved
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted providing that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Source our functions
. /usr/local/share/pcbsd/scripts/functions.sh

# Start by sourcing /etc/profile
# This grabs any HTTP_ / FTP_ PROXY variables
. /etc/profile

# Set the package command
pCmd="/usr/sbin/pkg"

# Fix some pkgs bugging us with license questions
PACKAGE_BUILDING=yes
export PACKAGE_BUILDING

intercept_pkg_dl()
{
   # Time to run pkgng and let it do its thing
   ${pCmd} $@
   result=$?

   # Make sure we run extract-overlay again
   pc-extractoverlay ports >/dev/null 2>/dev/null
   
   exit $result
}

# Parse the flags we are sending over to pkg
# will intercept the install / upgrade flags
# and use our internal function to download
# in a much faster method ;)
case $1 in
install|upgrade) intercept_pkg_dl ${@} ;;
              *) ${pCmd} ${@} 
                 exit $?
                 ;;
esac 
