#############################################################################
# Makefile for building: pc-systemflag
#############################################################################
PREFIX?= /usr/local

####### Install

all:

install_doinstall:
	sh install.sh $(PREFIX)

install: install_doinstall
