# New ports collection makefile for:	trueos-meta-nginx
#
# $FreeBSD$
#

PORTNAME=	trueos-meta-nginx
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port trueos-meta-nginx

RUN_DEPENDS=	nginx>=0:${PORTSDIR}/www/nginx

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
