# New ports collection makefile for:	pcbsd-meta-kde-calligra
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-kde-calligra
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-kde-calligra

RUN_DEPENDS=	calligra>=0:${PORTSDIR}/editors/calligra \
		calligra-l10n>=0:${PORTSDIR}/editors/calligra-l10n

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
