# New ports collection makefile for:	pcbsd-meta-enlightenment
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-enlightenment
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-enlightenment

RUN_DEPENDS=	enlightenment>=0:${PORTSDIR}/x11-wm/enlightenment

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
