# New ports collection makefile for:	trueos-meta-vmwareguest
#
# $FreeBSD$
#

PORTNAME=	trueos-meta-vmwareguest
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port trueos-meta-vmwareguest

RUN_DEPENDS=	open-vm-tools-nox11>=0:${PORTSDIR}/emulators/open-vm-tools-nox11
NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
