#!/usr/local/bin/php
<?
  exec("id -u", $output);
  if ( $output[0] != "0" )
     die("Must be run as root\n");

  $stdin = fopen('php://stdin', 'r');
  $user = $argv[1];
  if ( $argv[2] == "--" )
    $pass = trim(fgets(STDIN));
  else
    $pass = $argv[2];

  if ( empty($user) or empty($pass) )
     die("Usage: appcafe-setpass <username> <password>\n");

  $pfile = "username = " . $user . "\n" . "password = " . password_hash($pass, PASSWORD_DEFAULT);

  file_put_contents ( "/usr/local/etc/appcafe.pwd", $pfile );
  system("chown root:wheel /usr/local/etc/appcafe.pwd");
  system("chmod 644 /usr/local/etc/appcafe.pwd");
  echo "Password set!\n";
?>
