#!/bin/sh
# License: BSD
# Author: Kris Moore
# 

PATH="$PATH:/usr/local/bin:/usr/local/sbin"
export PATH

QTMPDIR="/var/tmp/appcafe"
QDISID="${QTMPDIR}/dispatch-id"

getdisid() {
  if [ "`id -u`" != "0" ] ; then exit 1; fi

  dd if=/dev/urandom count=1024 bs=1k | env LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 128 | head -n 1 > ${QDISID}
  chmod 600 ${QDISID}
  cat $QDISID >&1
  exit 0
}

# Check if the local process is root, and pass back dispatcher ID if so
getdisid

exit 0
