#!/bin/sh
# License: BSD
# Author: Kris Moore
# 
# Dispatch script, run as root, allows www process to run 
# specific commands with priv
#
# Also runs as a daemon to process the said commands that appcafe
# wants to have run

# queue commands
# <app> <origin> <flag> <target>
# app = pbi / pkg
# origin = www/firefox or other PBI/PKG origin
# flag = install/delete/info
# target = __system__ / <jailname>

PATH="$PATH:/usr/local/bin:/usr/local/sbin"
export PATH

# QUEUE File
QTMPDIR="/var/tmp/appcafe"
QLOGDIR="${QTMPDIR}/logs"
QLIST="${QTMPDIR}/dispatch-queue"
QDISID="${QTMPDIR}/dispatch-id"
QWRK="${QLIST}.working"
QRESULTS="${QLIST}.results"

init_daemon()
{
  # Appweb tmp dir
  if [ ! -d "$QTMPDIR" ] ; then
     mkdir ${QTMPDIR}
  fi
  if [ ! -d "$QLOGDIR" ] ; then
     mkdir ${QLOGDIR}
  fi

  chmod 600 ${QTMPDIR}
  chmod 600 ${QLOGDIR}

  # Cleanup some working / temp files
  for rmFile in ${QDISID} ${QLIST} ${QWRK}
  do
     if [ -e "$rmFile" ] ; then
       rm $rmFile
     fi
  done

  # Cleanup old daemon runtime
  for i in $QWRK $QRESULTS
  do
    if [ ! -e "$i" ] ; then
      touch $i
      chmod 600 $i
    fi
  done

  # Create the random string we will pass to authenticated clients
  # This changes after a login, and used to invalidate a previous login
  touch ${QDISID}
  chmod 600 ${QDISID}
  dd if=/dev/urandom count=1024 bs=1k | env LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 128 | head -n 1 > ${QDISID}

}

run_queue_cmd()
{
  # Breakdown the line into individual flags
  app=`echo $1 | cut -d " " -f 1`
  origin=`echo $1 | cut -d " " -f 2`
  flag=`echo $1 | cut -d " " -f 3`
  target=`echo $1 | cut -d " " -f 4`

  # Get the uniq identifier for this cmd
  local ident="`uuidgen`"
  QLOGFILE="${QLOGDIR}/${ident}.log"
  touch ${QLOGFILE}
  chmod 644 ${QLOGFILE}


  # Sanity check some of the given options
  case $app in
   pkg|pbi) case $flag in
            install|delete|info) ;;
                   *) echo "Unauthorized command specified: $1" >> ${QLOGFILE}
                      echo "FAILED $ident $@" >> $QRESULTS
                      return 1
                      ;;
            esac
            ;;
 pkgupdate) target="$origin" ;;
    iocage) case $origin in
	       destroy|pull) ;;
		   *) echo "Unauthorized iocage command specified: $1" >> ${QLOGFILE}
                      echo "FAILED $ident $@" >> $QRESULTS
                      return 1 ;;
	    esac
            ;;
         *) echo "Unauthorized command specified: $1" >> ${QLOGFILE}
            echo "FAILED $ident $@" >> $QRESULTS
            return 1
            ;;
  esac

  
  # Now build the command
  if [ "$app" == "pbi" ];then
     cmd="pbi"
     if [ "$flag" = "app" ] ; then flag="$flag --licagree"; fi
     if [ "$target" != "__system__" ] ; then
       cmd="$cmd $flag -j $target $origin"
     else
       cmd="$cmd $flag $origin"
     fi
  elif [ "$app" == "pkg" ];then
     cmd="pkg"
     if [ "$target" != "__system__" ] ; then
       cmd="$cmd -j $target"
     fi
     cmd="$cmd $flag -y $origin"
  elif [ "$app" == "pkgupdate" ];then
     cmd="pc-updatemanager pkgupdate"
     if [ "$target" != "__system__" ] ; then
       cmd="iocage pkgupdate $target"
     fi
  elif [ "$app" == "iocage" ];then
     if [ "$origin" = "pull" ] ; then
        neworigin="`echo $flag | sed 's|/|-|g'`"

	# First make sure this jail doesn't exist
	iocage get ip4_addr pbicage-$neworigin 2>/dev/null >/dev/null
        if [ $? -eq 0 ] ; then
	  echo "ERROR: The plugin jail pbicage-$neworigin is already installed!" >> ${QLOGFILE}
          echo "FAILED $ident $@" >> $QRESULTS
        fi	

        cmd="iocage pull $target tag=pbicage-$neworigin boot=yes ip4_addr=DEFAULT|AUTOIP4"
     fi 
     if [ "$origin" = "destroy" ] ; then
        # Stop the jail first
        iocage stop $target >>${QLOGFILE} 2>>${QLOGFILE}
	# Set the destroy command
	cmd="iocage destroy -f $target"
     fi
  fi

  # Remove any old ident lines from results
  sed -i '' "/ $ident /d" ${QRESULTS}

  # Lets run the command now
  echo "Running: $cmd" >>$QLOGFILE 2>>$QLOGFILE
  $cmd >>$QLOGFILE 2>>$QLOGFILE
  err=$?
  if [ $err -ne 0 ] ; then
     echo "FAILED $ident $@" >> $QRESULTS
  else
     echo "SUCCESS $ident $@" >> $QRESULTS
  fi

  # If we created a new jail, lets bootstrap iocage with pkgng
  if [ "$app" = "iocage" -a "$origin" = "create" -a $err -eq 0 ] ; then
     local jdir="/`cat ${QLOGFILE} | grep 'jail_zfs_dataset=' |cut -d '=' -f 2 | sed 's|/data$||g'`"
     bootstrap_pkgng_iocage "$jdir" >>${QLOGFILE} 2>>${QLOGFILE}
  fi

  # If we create a new plugin, lets start it now
  if [ "$app" = "iocage" -a "$origin" = "pull" -a $err -eq 0 ] ; then
     iocage start pbicage-$neworigin >>${QLOGFILE} 2>>${QLOGFILE}
  fi

  # Inform syscache of the updates to check
  syscache "startsync" >/dev/null 2>/dev/null

  # Save the log file for later diagnostics
  return $err
}

bootstrap_pkgng_iocage()
{
  local jaildir="${1}"
  local outfile="${1}/.pkgBS.sh"
  echo "Bootstrapping pkgng for jail ${jaildir}"

  if [ ! -e "${jaildir}/bin/freebsd-version" ] ; then
     echo "Missing /bin/freebsd-version in jail.."
     echo "PKG bootstrap can only be done on 10.0 and higher, skipping..."
     return 1
  fi

  # Setup the repo to use the XX.0-RELEASE pkgng branch
  local jrelease=`${jaildir}/bin/freebsd-version`
  echo "$jrelease" | grep -q "RELEASE"
  if [ $? -eq 0 ] ; then
    local release="`echo ${jrelease} | cut -d '-' -f 1 |  cut -d '.' -f 1`.0-RELEASE"
  else
    local release="`echo ${jrelease} | cut -d '-' -f 1-2`"
  fi
  local arch="$(uname -m)"

cat <<__EOF__ >"${outfile}"
#!/bin/sh
rm /etc/pkg/FreeBSD.conf 2>/dev/null >/dev/null

# Create the pkg.conf file
mkdir -p /usr/local/etc 2>/dev/null
echo "PKG_CACHEDIR: /usr/local/tmp
REPOS_DIR: [
                \"/usr/local/etc/pkg/repos\"
           ]" > /usr/local/etc/pkg.conf

# Create the repo dirs
mkdir -p /usr/local/etc/pkg/repos 2>/dev/null
mkdir -p /usr/local/etc/pkg/fingerprints/pcbsd/trusted 2>/dev/null
mkdir -p /usr/local/etc/pkg/fingerprints/pcbsd/revoked 2>/dev/null

# Save the repo configuration file
echo "pcbsd-major: {
               url: \"http://pkg.cdn.pcbsd.org/${release}/${arch}\",
               signature_type: \"fingerprints\",
               fingerprints: \"/usr/local/etc/pkg/fingerprints/pcbsd\",
               enabled: true
              }" > /usr/local/etc/pkg/repos/pcbsd.conf

# Create the repo.dist file
echo "pcbsd: {
               url: \"http://pkg.cdn.pcbsd.org/VERSION/ARCH\",
               signature_type: \"fingerprints\",
               fingerprints: \"/usr/local/etc/pkg/fingerprints/pcbsd\",
               enabled: true
              }" > /usr/local/etc/pkg/repos/pcbsd.conf.dist

# Save the fingerprint file
echo "function: sha256
fingerprint: b2b9e037f938cf20ba68aa85ac88c15889c729a7f6b70c25069774308e760a03" > /usr/local/etc/pkg/fingerprints/pcbsd/trusted/pkg.cdn.pcbsd.org.20131209

#pkg update -f

exit 0
__EOF__

  # Run the file to bootstrap pkg
  chroot $jaildir sh /.pkgBS.sh
  rm ${outfile}

  # Now boot-strap the real pkgng pkg
  pkg -c ${jaildir} install -qy ports-mgmt/pkg
}

run_daemon()
{
  pid="/var/run/appcafe-dispatcher.pid"

  # Check if we have another copy of the daemon running
  if [ -e "${pid}" ] ; then
     pgrep -F ${pid} >/dev/null 2>/dev/null
     if [ $? -eq 0 ] ; then return 0; fi
  fi
  echo "$$" > ${pid}

  # Setup the daemon files
  init_daemon

  # Run the main loop
  while :
  do
    # Check if we have anything to do?
    if [ ! -e "$QLIST" ] ; then
       sleep 10
       continue
    fi

    # Move the queue over and run it
    mv $QLIST ${QLIST}.tmp
    while read line
    do
       echo "$line" > $QWRK
       run_queue_cmd "$line"
       echo "" > $QWRK
    done < ${QLIST}.tmp
    rm ${QLIST}.tmp

    # Done with pkg ops, lets inform syscache to refresh
    syscache "startsync" >/dev/null 2>/dev/null
  done

  rm $pid
}

list_status()
{
  if [ -e "$QLIST" ] ; then
     cat ${QLIST}
  fi
  if [ -e "$QLIST.tmp" ] ; then
     cat ${QLIST}.tmp
  fi
}

list_results()
{
  if [ -e "$QRESULTS" ] ; then
    tail -50 ${QRESULTS}
  else
    echo ""
  fi
}

display_log()
{
  if [ -e "${QLOGDIR}/${1}.log" ] ; then
    cat ${QLOGDIR}/${1}.log
  else
    echo ""
  fi
}

run_iocage_cmd()
{
  case $2 in
      start) iocage start $3
	     iocage set boot=on $3
             ;;
       stop) iocage stop $3
	     iocage set boot=off $3
	     ;;
       auto) iocage set boot=on $3 ;;
        set) iocage set $3 $4 $5 $6;;
        get) iocage get $3 $4 $5 $6 ; exit $? ;;
          *) echo "Non-dispatch-approved iocage command: $2" ;;
  esac
  syscache "startsync" >/dev/null 2>/dev/null
}

run_service_cmd()
{

  local jid=""
  sname="$3"
  sscript="$4"
  if [ "$5" != "__system__" ] ; then
     jid="$5"
     jdir=`jls | grep " ${jid} " | awk '{print $4}'`
     rcfile="${jdir}/etc/rc.conf"
  else
     rcfile="/etc/rc.conf"
  fi

  case $2 in
       stop) # First, stop the service
	     if [ -n "$jid" ] ; then
	        jexec $jid service $sscript stop
             else
                service $sscript stop
	     fi 
	     # Now disable rc.conf entry
	     sed -i '' "/^${sname}_enable=\"YES\"/d" ${rcfile}
             ;;
      start) # First, enable the service
	     sed -i '' "/^${sname}_enable=\"NO\"/d" ${rcfile}
	     sed -i '' "/^${sname}_enable=\"YES\"/d" ${rcfile}
	     echo "${sname}_enable=\"YES\"" >> ${rcfile}

	     if [ -n "$jid" ] ; then
	        jexec $jid service $sscript start
             else
                service $sscript start
	     fi 
             ;;
    restart) # Restart the service 
	     if [ -n "$jid" ] ; then
	        jexec $jid service $sscript restart
             else
                service $sscript restart
             fi
             ;;
          *) echo "Non-dispatch-approved service command: $2" ;;
  esac
}

# Get value from config file
getcfg()
{
 cscript="$pbicdir/scripts/getconfig.sh"
 if [ ! -e "$cscript" ] ; then exit 1; fi

 if [ "$jail" != "__system__" ] ; then
    jid="$jail"
    jdir=`jls | grep " ${jid} " | awk '{print $4}'`
    rm ${jdir}/tmp/.appcafe-getcfg.sh.$$ >/dev/null 2>/dev/null
    cp $cscript ${jdir}/tmp/.appcafe-getcfg.sh.$$
    jexec $jid sh /tmp/.appcafe-getcfg.sh.$$ "$key"
    err=$?
    rm ${jdir}/tmp/.appcafe-getcfg.sh.$$
 else
   $cscript "$key"
   err=$?
 fi

 if [ $err -ne 0 ] ; then
   echo "Failed getting key: $key"
   exit 1
 fi
 exit 0
}

# Set value in config file
setcfg()
{
 cscript="$pbicdir/scripts/setconfig.sh"
 if [ ! -e "$cscript" ] ; then exit 1; fi
 if [ "$jail" != "__system__" ] ; then
    jid="$jail"
    jdir=`jls | grep " ${jid} " | awk '{print $4}'`
    rm ${jdir}/tmp/.appcafe-setcfg.sh.$$ >/dev/null 2>/dev/null
    cp $cscript ${jdir}/tmp/.appcafe-setcfg.sh.$$
    jexec $jid sh /tmp/.appcafe-setcfg.sh.$$ "$key" "$value"
    err=$?
    rm ${jdir}/tmp/.appcafe-setcfg.sh.$$
 else
   $cscript "$key" "$value"
   err=$?
 fi

 if [ $err -ne 0 ] ; then
   echo "Failed getting key: $key"
   exit 1
 fi
 exit 0
}

donecfg()
{
 cscript="$pbicdir/scripts/doneconfig.sh"
 if [ ! -e "$cscript" ] ; then exit 1; fi
 if [ "$jail" != "__system__" ] ; then
    jid="$jail"
    jdir=`jls | grep " ${jid} " | awk '{print $4}'`
    rm ${jdir}/tmp/.appcafe-donecfg.sh.$$ >/dev/null 2>/dev/null
    cp $cscript ${jdir}/tmp/.appcafe-donecfg.sh.$$
    jexec $jid sh /tmp/.appcafe-donecfg.sh.$$
    err=$?
    rm ${jdir}/tmp/.appcafe-donecfg.sh.$$
 else
   $cscript
   err=$?
 fi

 if [ $err -ne 0 ] ; then
   echo "Failed getting key: $key"
   exit 1
 fi
 exit 0
}

print_usage()
{
  echo "Dispatcher usage:
--------------------------------
   iocage {start|stop} {jail}
   queue {pkg|pbi} {origin} {install/delete/info} {__system__|<jailname>}
   pkgupdate {__system__|<jailname>}
   service {start|stop|restart} {servicetag} {servicerc} {__system__|<jid>}
   getcfg {pbicdir} {__system__|<jid>} {key}
   setcfg {pbicdir} {__system__|<jid>} {key} {value}
   donecfg {pbicdir} {__system__|<jid>}
   daemon
   status
   results 
   log {hash}
" 
}

# Login is requesting the dispatcher ID for security
# Check the username / password and if OK pass the ID back
getdisid() {
  # Verify the username / password match what is passed
  php /usr/local/share/appcafe/dispatcher-auth >/dev/null 2>/dev/null
  if [ $? -ne 0 ] ; then exit 1; fi

  dd if=/dev/urandom count=1024 bs=1k | env LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1 > ${QDISID}
  chmod 600 ${QDISID}
  cat $QDISID >&1
  exit 0
}

bad_disid() {
  echo "Invalid dispatcher ID!"
  exit 1
}

verify_disid() {
  # Check if we have a valid Dispatcher ID set
  if [ -z "$PHP_DISID" ] ; then bad_disid; fi
  if [ "$PHP_DISID" != "`cat $QDISID`" ] ; then bad_disid; fi
  return 0
}

if [ "`/usr/bin/id -u`" != "0" ] ; then
   echo "Must be run as root!"
   exit 1
fi

if [ -n "$PHP_DISID" ] ; then
  echo "$PHP_DISID" > /tmp/disID
fi

case $1 in
    # Figure out which iocage command we are using
    iocage) verify_disid
	    case $2 in
              # These commands will be queued
              destroy|pull) echo "$@" >>${QLIST} ;;
	      # These commands can be run immediately
	      start|stop|auto|set|get) run_iocage_cmd $@ ;;
	      *) echo "Invalid iocage command! $2" ; exit 1 ;;
	    esac
	    ;;
    # Commands that interact with services
   service) verify_disid
	    run_service_cmd $@ ;;
    # These commands interact with the dispatcher daemon
     queue) verify_disid
            echo "$@" | cut -d ' ' -f 2- >>${QLIST} ;;
 pkgupdate) verify_disid
	    echo "pkgupdate $2" >>${QLIST} ;;
    daemon) run_daemon ;;
       log) display_log "$2" ;;
    status) list_status ;;
   results) list_results ;;
    getcfg) verify_disid
	    pbicdir="$2" ; jail="$3" ; key="$4"
            getcfg ;;
    setcfg) verify_disid
	    pbicdir="$2" ; jail="$3" ; key="$4" ; value="$5"
            setcfg ;;
   donecfg) verify_disid
	    pbicdir="$2" ; jail="$3"
            donecfg ;;
  getdisid) getdisid ;;
  verify_disid) verify_disid
                exit $?
                ;;
         *) print_usage ; exit 1 ;;
esac

exit 0
