#!/bin/sh

if [ -z "$1" ] ; then
   STAGEDIR="/usr/local"
else
   STAGEDIR="$1"
fi

PROGDIR="${STAGEDIR}/share/appcafe"
rm -rf ${PROGDIR} >/dev/null 2>/dev/null
mkdir -p ${PROGDIR} >/dev/null 2>/dev/null

DIR=`dirname $0`
cd ${DIR}

# Copy dispatcher script
cp dispatcher ${PROGDIR}/dispatcher
chmod 755 ${PROGDIR}/dispatcher

cp -r share/* ${PROGDIR}/
cp -r vendor ${PROGDIR}/html/

if [ ! -d "${STAGEDIR}/etc/rc.d" ] ; then
   mkdir ${STAEGDIR}/etc/rc.d
fi
cp rc.d/* ${STAGEDIR}/etc/rc.d/

# Copy over the conf file
cp etc/appcafe.conf.dist ${STAGEDIR}/etc/appcafe.conf.dist

# Copy over the setpass util
if [ ! -d "${STAGEDIR}/bin" ] ; then
   mkdir ${STAEGDIR}/bin
fi

exit 0
