#############################################################################
# Makefile for building: appweb
#############################################################################

####### Install

PREFIX?= /usr/local

all:

install_doinstall:
	sh install $(PREFIX)

install:  install_doinstall
