# New ports collection makefile for:	trueos-meta-lighttp
#
# $FreeBSD$
#

PORTNAME=	trueos-meta-lighttp
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port trueos-meta-lighttp

RUN_DEPENDS=	lighttpd>=0:${PORTSDIR}/www/lighttpd

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
