.Dd November 24, 2015
.Dt JLS 8
.Os
.Sh NAME
.Nm pc-sysconfig
.Nd "Simple system configuration utility"
.Sh SYNOPSIS
.Nm
.Op Ar "command option1 option2" "command2 option1 option2" ...
.Op Fl "devinfo <device> [skiplabel]"
.Op Fl "mount <device> [<filesystem>] [<mountpoint>]"
.Sh DESCRIPTION
The
.Nm 
utility is a simple system 
configuration tool written for pc-bsd.  
.Pp
The available list commands available to you are
.Bl -tag -width indent 
.It \fBlist-remdev\fR 
List all removable devices attached to the system.
.It \fBlist-mounteddev\fR
List all removable devices that are currently mounted
.It \fBlist-audiodev\fR
List all available audio devices
.It \fBprobe-netdrives\fR
List all the available shared drives on the local network
.It \fBlist-mountednetdrives\fR
 List all the available shared drives which can currently be browsed (assuming the remote system is running properly)
.It \fBsupportedfilesystems\fR
List all the filesystems that are currently detected/supported
.It \fBdevinfo <device> [skiplabel]\fR
 Fetch device information (Filesystem, Label, Type)
.It \fBdevsize <device>\fR
Fetch space of mounted device
.It \fBusingtormode\fR
Returns whether or not the system is routing all traffic through tor as TRUE or FALSE
.It \fBgetscreenbrightness\fR
Returns the brightness of the first controllable screen as a percentage or "[ERROR]" otherwise
.It \fBsystemcansuspend\fR
Returns whether the system supports the S3 suspend state returns a TRUE or FALSE

.Pp
The available action commands available to you are
.It \fBmount <device> [<filesystem>] [<mountpoint>]\fR
This will mount the removable device on the system 
(with user-accessible permissions if the mountpoint 
needs to be created)
.Pp
If there is no filesystem set (or "auto" is 
used), it will try to use the one that is 
auto-detected for the device
.Pp
If there is no mountpoint set, it will assign a 
new mountpoint within the "/media/" directory based on 
the device label
.It \fBunmount <device or mountpoint> [force]\fR
This will unmount the removable device from the system
.Pp
This may be forced by using the "force" flag as 
well (this is never recommended but may be required in the case that 
hald is pinging the device and keeping it marked as active.)
.Pp
If the input device is a memory disk (/dev/md*), then 
it will automatically remove the memory disk from the 
system as well
.It \fBmountnet <IP of remote host> <Name of remote host>\fR
This will setup the remote host to be browsable on the 
local system with the given name
.Pp
Note that the remote host is automatically 
mounted/unmounted based on local user activity
.Pp
The remote host is automatically 
mounted/unmounted based on local user activity
.It \fBunmountnet <IP of remote host>\fR
This will remove the remote host from being browsable 
on the local system
.It \fBload-iso <path to iso>\fR
This will load the ISO file as a memory disk on the 
system making it available to mount
.Pp
The path must be an absolute path
.It \fBsuspendsystem\fR
Puts system in s3 suspend state
.It \fBsetscreenbrightness <percentage>\fR
This will set the brightness of all the available 
screens to the given percentage
.Pp
It is also possible to adjust the current value by 
supplying a [+/-] before the number
.Pp
Returns ERROR or SUCCESS based on whether or not it 
was able to make a change.
.E1
.Sh EXAMPLE
pc-sysconfig "setscreenbrightness +5"
.Pp
Will increase screen brightness by five percent for 
you and return SUCCESS if it works or ERROR if it 
can't find a display
