#!/bin/sh
# $FreeBSD$

# PROVIDE: appweb
# REQUIRE: LOGIN cleanvar
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable appweb:
# appweb_enable (bool):		Set to "NO" by default.
#				Set it to "YES" to enable appweb

. /etc/rc.subr

name="appweb"
rcvar=appweb_enable

command="/usr/local/sbin/nginx"
start_cmd="appweb_start"
stop_cmd="appweb_stop"
_pidprefix="/var/run"
pidfile="${_pidprefix}/${name}.pid"
_tmpprefix="/var/tmp/nginx"
appweb_dir="/usr/local/share/appweb"
required_files="/usr/local/share/appweb/nginx.conf"

[ -z "$appweb_enable" ]		&& appweb_enable="NO"

load_rc_config $name

nginx_checktmpdir()
{
        if [ ! -d ${_tmpprefix} ] ; then
                install -d -o www -g www -m 755 ${_tmpprefix}
        fi
}

appweb_start()
{
  nginx_checktmpdir

  # Ugly, I know, needs to be replaced
  /usr/local/etc/rc.d/php-fpm status >/dev/null 2>/dev/null
  if [ $? -ne 0 ] ; then
     /usr/local/etc/rc.d/php-fpm onerestart
  fi

  $command -c /usr/local/share/appweb/nginx.conf -g "pid /var/run/appweb.pid;"

  # Start the dispatcher also
  ( ${appweb_dir}/dispatcher daemon )&
}

appweb_stop()
{
  kill -QUIT $(cat /var/run/appweb.pid)
  kill -9 $(cat /var/run/appweb-dispatcher.pid)
}

run_rc_command "$1"
