# New ports collection makefile for:	pcbsd-meta-ratpoison
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-ratpoison
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-ratpoison

RUN_DEPENDS=	ratpoison>=0:${PORTSDIR}/x11-wm/ratpoison

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
