# New ports collection makefile for:	pcbsd-meta-enlightenment-modules
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-enlightenment-modules
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-enlightenment-modules

RUN_DEPENDS=	e17-modules>=0:${PORTSDIR}/x11-wm/e17-modules

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
