#!/bin/sh
#
# $FreeBSD: editors/openoffice-devel/files/openoffice-wrapper 300896 2012-07-14 13:54:48Z beat $

oopath=%%PREFIX%%/%%INSTALLATION_BASEDIR%%/%%OOODIR%%
program=`echo $0 | sed -e 's|.*-%%SVNREVISION%%-||'`

case $program in
$0)
	$oopath/program/soffice "$@"
	;;
setofficelang)
	$oopath/basis-link/program/$program "$@"
	;;
*)
	$oopath/program/$program "$@"
	;;
esac
