# New ports collection makefile for:	pcbsd-meta-kde-games
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-kde-games
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-kde-games

RUN_DEPENDS=	kdegames>=0:${PORTSDIR}/games/kdegames4 \
		gnugo>=0:${PORTSDIR}/games/gnugo

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
