# New ports collection makefile for:	pcbsd-meta-windowlab
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-windowlab
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-windowlab

RUN_DEPENDS=	windowlab>=0:${PORTSDIR}/x11-wm/windowlab
NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
