# New ports collection makefile for:	pcbsd-meta-kde-webdevkit
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-kde-webdevkit
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-kde-webdevkit

RUN_DEPENDS=	kdesdk>=0:${PORTSDIR}/devel/kdesdk4

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
