# New ports collection makefile for:	pcbsd-meta-evilwm
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-evilwm
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-evilwm

RUN_DEPENDS=	evilwm>=0:${PORTSDIR}/x11-wm/evilwm

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
