# New ports collection makefile for:	pcbsd-meta-kde-multimedia
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-kde-multimedia
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-kde-multimedia

RUN_DEPENDS=	kdemultimedia>=0:${PORTSDIR}/multimedia/kdemultimedia4 \
		amarok>=0:${PORTSDIR}/audio/amarok-kde4

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
