#!/bin/sh
# Bring up the default printer config application
# License: BSD

#Check if the HPLIP ppd files are also available, and link them into the CUPS database
if [ -e /usr/local/share/ppd/HP ]; then
  ln -sf /usr/local/share/ppd/HP /usr/local/share/cups/model/HPLIP
elif [ -e /usr/local/share/cups/model/HPLIP ]; then
  rm /usr/local/share/cups/model/HPLIP
fi
user=$1

system-config-printer
