#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ldconfig
# REQUIRE: mountcritremote FILESYSTEMS
# BEFORE:  DAEMON

. /etc/rc.subr

name="ldconfig"
ldconfig_command="/sbin/ldconfig"
start_cmd="ldconfig_start"
stop_cmd=":"

ldconfig_start()
{
	ldconfig_paths="/usr/lib/compat ${PBI_RUNDIR}/local/lib ${PBI_RUNDIR}/local/lib/compat/pkg"
	ldconfig_local_dirs="${PBI_RUNDIR}/local/libdata/ldconfig"
	ldconfig_local32_dirs="${PBI_RUNDIR}/local/libdata/ldconfig32"
	ldconfig_file="/var/run/ld-elf.so.hints.`basename ${PBI_RUNDIR}`"
	ldconfig32_file="/var/run/ld-elf32.so.hints.`basename ${PBI_RUNDIR}`"

	local _files _ins

	_ins="-i"
	ldconfig=${ldconfig_command}
	if [ -x "${ldconfig_command}" ]; then
		_LDC="/lib /usr/lib"
		for i in ${ldconfig_local_dirs}; do
			if [ -d "${i}" ]; then
				_files=`find ${i} -type f`
				if [ -n "${_files}" ]; then
					ldconfig_paths="${ldconfig_paths} `cat ${_files} | sort -u`"
				fi
			fi
		done
		for i in ${ldconfig_paths} /etc/ld-elf.so.conf; do
			if [ -r "${i}" ]; then
				_LDC="${_LDC} ${i}"
			fi
		done
		_LDC=`echo $_LDC | sed "s|/usr/local|${PBI_RUNDIR}/local|g"`
		check_startmsgs && echo 'ELF ldconfig path:' ${_LDC}
		${ldconfig} -elf ${_ins} -f ${ldconfig_file} ${_LDC}

		case `sysctl -n hw.machine_arch` in
		amd64)
			for i in ${ldconfig_local32_dirs}; do
				if [ -d "${i}" ]; then
					_files=`find ${i} -type f`
					if [ -n "${_files}" ]; then
						ldconfig32_paths="${ldconfig32_paths} `cat ${_files} | sort -u`"
					fi
				fi
			done
			_LDC=""
			for i in ${ldconfig32_paths}; do
				if [ -r "${i}" ]; then
					_LDC="${_LDC} ${i}"
				fi
			done
			check_startmsgs &&
			    echo '32-bit compatibility ldconfig path:' ${_LDC}
			_LDC=`echo $_LDC | sed "s|/usr/local|${PBI_RUNDIR}/local|g"`
			${ldconfig} -32 -m ${_ins} -f ${ldconfig32_file} ${_LDC}
			;;
		esac

		# Legacy aout support for i386 only
		case `sysctl -n hw.machine_arch` in
		i386)
			# Default the a.out ldconfig path.
			: ${ldconfig_paths_aout=${ldconfig_paths}}
			_LDC=""
			for i in /usr/lib/aout ${ldconfig_paths_aout} /etc/ld.so.conf; do
				if [ -r "${i}" ]; then
					_LDC="${_LDC} ${i}"
				fi
			done
			check_startmsgs && echo 'a.out ldconfig path:' ${_LDC}
			${ldconfig} -aout ${_ins} ${_LDC}
			;;
		esac
	fi
}

load_rc_config $name
run_rc_command "$1"
