#!/bin/sh
# PC-BSD Helper script to open files with default mime type
###########################################################

unset LD_LIBRARY_PATH
unset LD_32_LIBRARY_PATH
unset LD_ELF_HINTS_PATH
unset LD_32_ELF_HINTS_PATH
unset LD_PRELOAD
unset LD_32_PRELOAD
unset LD_PBIPRELOAD
unset PBI_RUNDIR
PBI_BREAKOUT="YES" ; export PBI_BREAKOUT

/usr/local/bin/xdg-open "$1"
