#!/bin/sh

check_nvidia_linux()
{
   # XXX this needs to be reworked
   # Check if this PBI even has a linux compat layer with GL support
   if [ ! -d "${1}/linux/usr/lib" ] ; then return; fi
   ls ${1}/linux/usr/lib/libGL* 2>/dev/null >/dev/null
   if [ $? -ne 0 ] ; then return ; fi

   # Ok, we have linux compat in the PBI, is the system using nvidia?
   pkg info -e nvidia-driver
   if [ $? -ne 0 ] ; then return ; fi

   # We have nvidia, lets do our linux lib population now
   for i in `pkg info -l nvidia-driver 2>/dev/null | grep 'compat/linux/usr/lib' | awk '{print $1}'`
   do
      cp ${i} ${1}/linux/usr/lib/
   done
}

if [ -z "$PBI_RUNDIR" -o -z "$PBI_PRELOAD" -o -z "$LD_ELF_HINTS_PATH" ] ; then
   echo "ERROR: Missing env settings..."
   exit 1
fi

# Basic script to init the PBI environment, basically that just involves setting
# up ldconfig stuff
#/etc/rc.d/ldconfig start
