#!/bin/sh
# PC-BSD Helper script to open files with default mime type
###########################################################

target="$1"

unset LD_LIBRARY_PATH
unset LD_PRELOAD
unset PBI_PRELOAD
unset PBI_RUNDIR
PBI_BREAKOUT="YES" ; export PBI_BREAKOUT

echo $target | grep -e "^http" -e "^ftp" -e "^mailto:" >/dev/null 2>/dev/null
if [ $? -eq 0 ] ; then
  # Opening a link
  echo "/usr/local/bin/xdg-open $target" | /bin/sh
  if [ $? -ne 0 ] ; then
	zenity --error --title "Open URL error" --text "Could not locate any known browser!"
  fi
else
  # Opening a file
  echo "gvfs-open $target" | /bin/sh
  if [ $? -ne 0 ] ; then
        ext=`echo $target | awk -F . '{print $NF}'`
	zenity --error --title "File association error" --text "The file extension (.${ext}) has no associated program!"
  fi
fi

