#!/bin/sh
# PC-BSD Helper script to open commands outside the container
#############################################################
unset LD_LIBRARY_PATH
unset LD_32_LIBRARY_PATH
unset LD_ELF_HINTS_PATH
unset LD_32_ELF_HINTS_PATH
unset LD_PRELOAD
unset LD_32_PRELOAD
unset LD_PBIPRELOAD
unset PBI_RUNDIR
export PBI_BREAKOUT="YES"

$@
