#############################################################################
# Makefile for building: pc-sysinstall
#############################################################################

####### Install

all:

install_doinstall:
	sh install.sh

install: install_doinstall
