# New ports collection makefile for:	trueos-meta-owncloud
#
# $FreeBSD$
#

PORTNAME=	trueos-meta-owncloud
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port trueos-meta-owncloud

RUN_DEPENDS=	owncloud>=0:${PORTSDIR}/www/owncloud

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
