#!/bin/sh

# PROVIDE: pcdm
# REQUIRE: LOGIN cleanvar moused syscons dbus
# KEYWORD: shutdown
# Add the following to /etc/rc.conf to start PCDM at boot time:
#
# pcdm_enable="YES"
#

. /etc/rc.subr

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

name="pcdm"
rcvar=pcdm_enable
command="/usr/local/sbin/PCDMd"
pidfile="/var/run/PCDMd.pid"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

load_rc_config ${name}
: ${pcdm_enable:=no} #default to not start pcdm automatically

pcdm_start()
{
  if ! checkyesno pcdm_enable ; then
     return 0
  fi

  # Check if boot-loader set option to skip xorg
  if [ "`kenv noxorg 2>/dev/null`" = "YES" ] ; then
     return 0
  fi

  echo "Starting PCDM."

  (
    iter=0
    while ! ps -axoargs | grep "^/usr/libexec/getty " | grep -qv grep >/dev/null 2>&1; do
	if [ ${iter} -eq 60 ]; then
	    break
	fi
	sleep 1
	iter=$(expr ${iter} + 1)
    done
    iter=0
    while ! /usr/local/bin/lshal >/dev/null 2>&1 ; do
	if [ ${iter} -eq 60 ]; then
	    break
	fi
	sleep 1
	iter=$(expr ${iter} + 1)
    done

    #Start the PCDM login daemon
    ${command} ${pcdm_flags} 
  ) &

}

pcdm_stop()
{
  #Send the PCDM daemon the signal not to start a new session after this one finishes
  ${command} stop
}

run_rc_command "$1"
