# New ports collection makefile for:	pcbsd-meta-development-debug
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-development-debug
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-development-debug

RUN_DEPENDS=	valgrind>=0:${PORTSDIR}/devel/valgrind

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
