# New ports collection makefile for:	trueos-meta-postgresql
#
# $FreeBSD$
#

PORTNAME=	trueos-meta-postgresql
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port trueos-meta-postgresql

RUN_DEPENDS=	postgresql-server>=0:${PORTSDIR}/databases/postgresql90-server

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
