#!/bin/sh
# Script to startup the first run setup gui 

# Check if we need to save an existing .xinitrc file
if [ -e "/root/.xinitrc" ] ; then
 mv /root/.xinitrc /root/.xinitrc.xbak
fi

# Check if we need to move the .fluxbox profile
if [ -e "/root/.fluxbox" ] ; then
  rm -rf /root/.fluxbox.xbak 2>/dev/null
  mv /root/.fluxbox /root/.fluxbox.xbak 2>/dev/null
fi

# Copy the default fluxbox init files
cp -R /usr/local/share/pcbsd/fluxboxinit /root/.fluxbox

# Make sure we use files in /root
HOME="/root"
export HOME

# Create the .xinitrc file
echo '# Set all our path variables
PATH="/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/bin:/usr/local/sbin"
HOME="/root"
export PATH HOME

# Unset the PROGDIR variable
PROGDIR=""
export PROGDIR

if [ -e "/root/.xprofile" ] ; then . /root/.xprofile ; fi

# Figure out which intro video to play
res=`xdpyinfo | grep dimensions: | awk "{print $2}"`
h=`echo $res | cut -d "x" -f 1`
w=`echo $res | cut -d "x" -f 2`
h=`expr 100 \* $h`
ratio=`expr $h \/ $w | cut -c 1-2`
case $ratio in
   13) mov="PCBSD9_4-3_UXGA.flv";;
   16) mov="PCBSD9_16-10_WUXGA.flv";;
   17) mov="PCBSD9_16-9_1080p.flv";;
    *) mov="PCBSD9_4-3_UXGA.flv";;
esac

# Play the video now
mplayer -fs -nomouseinput -zoom /usr/local/share/pcbsd/movies/$mov

# Setting a language
if [ -e "/etc/pcbsd-lang" ] ; then
   LANG=`cat /etc/pcbsd-lang`
   export LANG
fi

# Start fluxbox
/usr/local/bin/startfluxbox &
PID=$!

# Start first-boot wizard
/usr/local/bin/pc-firstboot
if [ $? -eq 0 ] ; then
  rm /var/.pcbsd-firstgui
fi
kill -9 ${PID}' > /root/.xinitrc
chmod 755 /root/.xinitrc
startx


# Put back our saved files
rm /root/.xinitrc >/dev/null 2>/dev/null
# Check if we need to save an existing .xinitrc file
if [ -e "/root/.xinitrc.xbak" ] ; then
   mv /root/.xinitrc.xbak /etc/.xinitrc
fi

# Check if we need to move the .fluxbox profile
if [ -e "/root/.fluxbox.xbak" ] ; then
  rm -rf /root/.fluxbox >/dev/null 2>/dev/null
  mv /root/.fluxbox.xbak /root/.fluxbox
fi
