#!/bin/sh

# Action can be add / del
action=$1
cdev=$2

regen_ossconf()
{
PCM_OSS_CONF_DIR=/compat/linux/etc/alsa/pcm/
PCM_OSS_CONF=${PCM_OSS_CONF_DIR}pcm-oss.conf

if [ ! -d $PCM_OSS_CONF_DIR ]; then
  return
fi

PCM=`egrep -o 'pcm[0-9]+' /dev/sndstat | egrep -o '[0-9]+'`
OSSCONF=`cat <<EOF
# pcm-oss plugin configuration
# generated by ${0}

pcm.oss {
        type oss
        device /dev/dsp
        hint {
                description "Open Sound System"
        }
}

ctl.oss {
        type oss
        device /dev/mixer
        hint {
                description "Open Sound System"
        }
}
EOF`

for NUM in $PCM; do
  UNIT_DESC=`sysctl -in dev.pcm.${NUM}.%desc`
  
  OSSCONF_UNITS=${OSSCONF_UNITS}`cat <<EOF

 
pcm.oss${NUM} {
	type oss
	device /dev/dsp${NUM}
	hint {
		description "oss${NUM}: ${UNIT_DESC}"
	}
}

ctl.oss${NUM} {
	type oss
	device /dev/mixer${NUM}
	hint {
		description "oss${NUM}: ${UNIT_DESC}"
	}
}
EOF`
done

echo "${OSSCONF}${OSSCONF_UNITS}" > $PCM_OSS_CONF
}

set_new_dev()
{
   # Dont keep changing the device at bootup, wait until after the system loads before enabling this
   ps -axoargs | grep -q "^/usr/libexec/getty "
   if [ $? -ne 0 ] ; then
      return
   fi

   mixerNum=`echo ${cdev} | egrep -o '[0-9]+'`

   # Can new dev play?
   cat /dev/sndstat | grep pcm${mixerNum} | grep -q play
   if [ $? -ne 0 ] ; then
      return
   fi

   # make new device the default one
   sysctl hw.snd.default_unit=$mixerNum

   # Look for pulseaudio daemons to change audio sinks on
   for user in `ps -auwwx | grep 'pulseaudio --start' | grep -v 'grep' | awk '{print $1}'`
   do
      su $user -c "pactl set-default-sink $mixerNum"
   done

}

# Update device based upon action
case $action in
   add) set_new_dev ;;
     *) ;;
esac

# Re-Create the linux OSS conf
regen_ossconf

exit 0
