.Dd Apr 15, 2010
.Dt PBI_ADD 1
.Os
.Sh NAME
.Nm pbi_add
.Nd Install a PBI file
.Sh SYNOPSIS
.Nm
.Op Fl f
.Op Fl i
.Op Fl j
.Op Fl J
.Op Fl l
.Op Fl v
.Op Fl -licagree
.Op Ar pbi
.Sh DESCRIPTION
The utility,
.Nm ,
installs, extracts or displays information about a PBI file
.Sh OPTIONS
.Bl -tag -width indent
.It Fl f
Force installation, overwriting an already installed copy of the application
.It Fl i
Display information about this PBI file
.It Fl l
Display LICENSE information for this PBI file.
.It Fl j Ar jail
Install target PBI into jail <jail>
.It Fl J
Create a new jail automatically via Warden, and install PBI into it
.It Fl v
Enable verbose output
.It Fl -licagree
Accept the license to install a PBI
.El
.Sh NOTES
For details about the module format, please refer to the wiki guide:
http://wiki.pcbsd.org/index.php/PBI_Module_Builder_Guide
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_delete 1 ,
.Xr pbi_info 1
