.Dd Apr 15, 2010
.Dt PBI_DELETE 1
.Os
.Sh NAME
.Nm pbi_delete
.Nd Removes an installed PBI
.Sh SYNOPSIS
.Nm
.Op Fl f
.Op Fl j Ar jail
.Op Fl v
.Op Ar pbi
.Sh DESCRIPTION
The utility,
.Nm ,
is used to remove an installed PBI file from the system.
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Fl f
Force removal of a PBI pkg even if it has deps
.It Fl j Ar jail
Delete PBI/PKG from the jail <jail>
.It Fl v
Enable verbose output
.El
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_icon 1 ,
.Xr pbi_info 1
