.Dd May 13, 2015
.Dt PBI_UPDATEINDEX 1
.Os
.Sh NAME
.Nm pbi_updateindex
.Nd Checks and updates the local PBI index from remote
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The utility,
.Nm ,
is used to update the local PBI index files. If the current
index is already installed, it will do nothing. 
.Pp
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_icon 1 ,
.Xr pbi_info 1
