.Dd May 13, 2015
.Dt PBI_MAKEINDEX 1
.Os
.Sh NAME
.Nm pbi_makeindex Ar OpenSSLKey
.Nd Creates the PBI index files and signs them with provided key
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The utility,
.Nm ,
is used to generate a PBI-INDEX file within the pbi-modules directory.
The resulting files are then signed and compressed, ready for placement
in the root directory for the associated package repo.
.Pp
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_icon 1 ,
.Xr pbi_info 1
