#!/bin/sh
# Login daemon for PCDM
# This listens for system login prompts and starts the main PCDM UI appropriately
#------------------------------------

PCDMCONF="/usr/local/etc/pcdm.conf"

#See if XDMCP support is enabled for logging in to this system
XDMCP=`grep "^ALLOW_REMOTE_LOGIN=" ${PCDMCONF} 2>/dev/null | cut -d '=' -f 2`
if [ "$XDMCP" = "TRUE" ]; then
  # XDMCP is enabled
  echo "Starting PCDM XDMCP Server"
  while [ ! -e /var/run/nologin ]; do
    xinit /usr/local/bin/PCDM-session --once -- /usr/local/bin/X :0 -displayfd /usr/local/share/PCDM/.xdisplay -indirect ${HOST}
  done
else
  # No XDMCP Enabled

  # Allow Auto-Login the first time PCDM starts
  touch /tmp/.PCDMAutoLogin
  # Now start the X Server
  while [ ! -e /var/run/nologin ]; do
    /usr/local/bin/pc-checkxdisplay
    xinit /usr/local/bin/PCDM-session --once -- :0  
  done
fi
	
