#!/bin/sh
# Login daemon for PCDM
# This listens for system login prompts and starts the main PCDM UI appropriately
#------------------------------------

#See if XDMCP support is enabled for logging in to this system
if [ -f /usr/local/share/PCDM/pcdm.conf .and. -z "`grep ALLOW_REMOTE_LOGIN=TRUE /usr/local/share/PCDM/pcdm.conf`"]; 
then
  # XDMCP is enabled
  echo "Starting PCDM XDMCP Server"
  while [ 1 ]; do
    xinit /usr/local/bin/PCDM-session -- /usr/local/bin/X :0 -displayfd /usr/local/share/PCDM/.xdisplay -indirect ${HOST}
  done
else
  # No XDMCP support

  # Allow Auto-Login the first time PCDM starts
  touch /tmp/.PCDMAUTOLOGINFILE
  # Now start the X Server
  while [ 1 ]; do
    /usr/local/bin/pc-checkxdisplay
    xinit /usr/local/bin/PCDM-session -- :0  
  done
fi
	
