# New ports collection makefile for:	pcbsd-meta-development-vcs
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-development-vcs
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-development-vcs

RUN_DEPENDS=	git>=0:${PORTSDIR}/devel/git \
		mercurial>=0:${PORTSDIR}/devel/mercurial

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
