# New ports collection makefile for:	trueos-meta-development
#
# $FreeBSD$
#

PORTNAME=	trueos-meta-development
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port trueos-meta-development

RUN_DEPENDS=	distcc>=0:${PORTSDIR}/devel/distcc \
		ccache>=0:${PORTSDIR}/devel/ccache

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
