# New ports collection makefile for:	pcbsd-meta-xfce-plugins
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-xfce-plugins
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-xfce-plugins

RUN_DEPENDS=	xfce4-notes-plugin>=0:${PORTSDIR}/deskutils/xfce4-notes-plugin \
		xfce4-weather-plugin>=0:${PORTSDIR}/misc/xfce4-weather-plugin \
		xfce4-messenger-plugin>=0:${PORTSDIR}/net-im/xfce4-messenger-plugin \
		xfce4-cpugraph-plugin>=0:${PORTSDIR}/sysutils/xfce4-cpugraph-plugin \
		xfce4-fsguard-plugin>=0:${PORTSDIR}/sysutils/xfce4-fsguard-plugin \
		xfce4-genmon-plugin>=0:${PORTSDIR}/sysutils/xfce4-genmon-plugin \
		xfce4-netload-plugin>=0:${PORTSDIR}/sysutils/xfce4-netload-plugin \
		xfce4-systemload-plugin>=0:${PORTSDIR}/sysutils/xfce4-systemload-plugin \
		xfce4-clipman-plugin>=0:${PORTSDIR}/x11/xfce4-clipman-plugin \
		xfce4-screenshooter-plugin>=0:${PORTSDIR}/x11/xfce4-screenshooter-plugin \
		xfce4-verve-plugin>=0:${PORTSDIR}/x11/xfce4-verve-plugin \
		xfce4-dev-tools>=0:${PORTSDIR}/devel/xfce4-dev-tools \
		xfce4-xkb-plugin>=0:${PORTSDIR}/deskutils/xfce4-xkb-plugin \
		xfce4-taskmanager>=0:${PORTSDIR}/x11/xfce4-taskmanager \
		xfce4-xmms-plugin>=0:${PORTSDIR}/multimedia/xfce4-xmms-plugin \
		xfce4-battery-plugin>=0:${PORTSDIR}/sysutils/xfce4-battery-plugin \
		xfce4-datetime-plugin>=0:${PORTSDIR}/x11-clocks/xfce4-datetime-plugin \

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
