#!/bin/sh
# Copyright (c) 2015 Kris Moore (iXsystems / PC-BSD)
# License: BSD

rules="/etc/ipfw.rules"

if [ -e "$rules" ] ; then
   echo "${rules} already exists!"
   echo "Remove this file first to re-generate ruleset"
   exit 1
fi

echo "Creating $rules."

cat >${rules} << EOF
#!/bin/sh
# To re-apply rules, you can run "sh ${rules}"

# Flush out the list before we begin.
ipfw -q -f flush

# Set rules command prefix
cmd="ipfw -q add"

# No restrictions on loopback
####################################################################
\$cmd 00020 allow all from any to any via lo0
####################################################################

# Catch spoofing from outside
####################################################################
\$cmd 00025 deny ip from any to any not antispoof in
####################################################################

# Check the state of packets
####################################################################
\$cmd 00050 check-state
\$cmd 00100 allow tcp from any to any established
####################################################################

# Allow all outgoing packets
####################################################################
\$cmd 00150 allow ip from any to any out keep-state
####################################################################

# Allow specific ports IN now
# Add here for any incoming services
####################################################################
#\$cmd 00400 allow tcp from any to me 22 in keep-state
#\$cmd 00405 allow tcp from any to me 80 in keep-state
####################################################################

# Deny all other incoming troublemakers
####################################################################
\$cmd 00500 deny log all from any to any
####################################################################

EOF
