#!/bin/sh
# Script to setup IPFW to for TOR forwarding
# Copyright (c) 2015 Kris Moore (iXsystems / PC-BSD)
# License: BSD

rules="/etc/ipfw.rules"

if [ -e "$rules" ] ; then
   mv ${rules} ${rules}.previous
fi

# Init the TOR database and such
rm -r /var/db/tor /var/run/tor
mkdir -p /var/db/tor/data /var/run/tor
touch /var/log/tor
chown -R _tor:_tor /var/db/tor /var/log/tor /var/run/tor
chmod -R 700 /var/db/tor

# Prevent sequential IP ids
sysctl net.inet.ip.random_id=1
grep -q 'net.inet.ip.random_id=' /etc/sysctl.conf
if [ $? -ne 0 ] ; then
  echo "net.inet.ip.random_id=1" >> /etc/sysctl.conf
fi

# Make sure TOR is enabled
sysrc -f /etc/rc.conf tor_enable="YES"

# Enable socat for DNS resolving
sysrc -f /etc/rc.conf socat_enable="YES"
sysrc -f /etc/rc.conf socat_flags="UDP4-RECVFROM:53,fork UDP4-SENDTO:localhost:9530"

# Make sure we have the default torrc file
cp /usr/local/share/pcbsd/conf/torrc /usr/local/etc/tor/torrc

echo "Creating $rules."

cat >${rules} << EOF
#!/bin/sh
# To re-apply rules, you can run "sh ${rules}"

# Flush out the list before we begin.
ipfw -q -f flush

# Set rules command prefix
cmd="ipfw -q add"

# Allow TOR to go in <-> out
####################################################################
\$cmd 00010 allow ip from any to any uid _tor out keep-state
####################################################################

# Forward all TCP packets to TOR, keep state
####################################################################
\$cmd 00030 fwd 127.0.0.1,9040 tcp from any to any out keep-state
####################################################################

# Allow everything to localhost
####################################################################
\$cmd 00050 allow all from localhost to localhost via lo0
####################################################################

# Check the state of packets
####################################################################
\$cmd 00050 check-state
\$cmd 00100 allow ip from any to any established
\$cmd 00115 allow udp from any to localhost 53 keep-state
####################################################################

# Deny all other incoming troublemakers
####################################################################
\$cmd 01500 deny log all from any to any
####################################################################

EOF

# Now setup DNS resolving
if [ ! -e "/etc/resolv.conf.preTor" ] ; then
  touch /etc/resolv.conf
  cp /etc/resolv.conf /etc/resolv.conf.preTor
fi
echo "nameserver 127.0.0.1" > /etc/resolv.conf

# Massage the dhclient.conf
if [ -e "/etc/dhclient.conf" ] ; then
  if [ ! -e "/etc/dhclient.conf.preTor" ] ; then
    cp /etc/dhclient.conf /etc/dhclient.conf.preTor
  fi
  cat /etc/dhclient.conf | grep -v "supersede domain-name-servers" > /etc/dhclient.conf.new
  mv /etc/dhclient.conf.new /etc/dhclient.conf
fi
echo "supersede domain-name-servers 127.0.0.1;" >> /etc/dhclient.conf

# Now lets apply the rules immediately
service ipfw onerestart
sh ${rules}

# Now start the TOR Service
service tor start
service socat start
