#!/bin/sh
# Copyright (c) 2015 Kris Moore (iXsystems / PC-BSD)
# License: BSD

rules="/etc/ipfw.rules"

if [ -e "$rules" ] ; then
   mv ${rules} ${rules}.previous
fi

echo "Creating $rules."

cat >${rules} << EOF
#!/bin/sh
# To re-apply rules, you can run "sh ${rules}"

# Flush out the list before we begin.
ipfw -q -f flush

# Set rules command prefix
cmd="ipfw -q add"

# No restrictions on loopback
####################################################################
\$cmd 00020 allow all from any to any via lo0
####################################################################

# Catch spoofing from outside
####################################################################
\$cmd 00025 deny ip from any to any not antispoof in
####################################################################

# Check the state of packets
####################################################################
\$cmd 00050 check-state
\$cmd 00100 allow tcp from any to any established
####################################################################

# Allow all outgoing packets
####################################################################
\$cmd 00150 allow ip from any to any out keep-state
####################################################################

# Allow specific ports IN now
# Add items to /etc/ipfw.openports in the format
# {tcp|udp} <portnum>
####################################################################
nextnum=200
if [ -e "/etc/ipfw.openports" ] ; then
  while read line
  do
    echo \$line | grep -q "^#"
    if [ \$? -eq 0 ] ; then continue ; fi
    proto="\`echo \$line | awk '{print \$1}'\`"
    port="\`echo \$line | awk '{print \$2}'\`"
    if [ -z "\$proto" -o -z "\$port" ] ; then continue ; fi
    \$cmd \$nextnum allow \$proto from any to me \$port in keep-state
    nextnum=\`expr \$nextnum + 1\`
  done < /etc/ipfw.openports
fi
####################################################################

# Deny all other incoming troublemakers
####################################################################
\$cmd 01500 deny log all from any to any
####################################################################

EOF

# If reverting from TOR mode, lets do some cleanup
if [ -e "/etc/resolv.conf.preTor" ]; then
  mv /etc/resolv.conf.preTor /etc/resolv.conf

  # Stop TOR / SOCAT services
  service tor stop
  service socat stop

  # Cleanup rc.conf
  sysrc -f /etc/rc.conf -x tor_enable
  sysrc -f /etc/rc.conf -x socat_enable
  sysrc -f /etc/rc.conf -x socat_flags
fi

# If reverting from TOR mode, put back the dhclient config
if [ -e "/etc/dhclient.conf.preTor" ]; then
  mv /etc/dhclient.conf.preTor /etc/dhclient.conf
fi

# Start IPFW now
service ipfw restart
sh ${rules}
