# New ports collection makefile for:	trueos-meta-wordpress
#
# $FreeBSD$
#

PORTNAME=	trueos-meta-wordpress
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port trueos-meta-wordpress

RUN_DEPENDS=	wordpress>=0:${PORTSDIR}/www/wordpress

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
