#!/bin/sh
# Login daemon for PCDM
# This starts the main PCDM UI appropriately
#------------------------------------

PCDMCONF="/usr/local/etc/pcdm.conf"
BASEPCDMAUTHFILE="/tmp/.PCDMAuth"
STOPFILE="/tmp/.PCDMstop"

#Quick check that this is not the "stop" command
if [ "${1}" = "stop" ]; then
  touch ${STOPFILE}
  exit
fi

XOPTS=""
grep -q "^ENABLE_TCP_LISTEN=TRUE" ${PCDMCONF}
if [ $? -ne 0 ]; then
  XOPTS="-nolisten tcp" 
fi

#See if VNC support is enabled for logging in to this system
grep -q "^ALLOW_REMOTE_LOGIN=TRUE" ${PCDMCONF}
if [ $? -eq 0 ]; then
   # Setup default vnc server opts
   vncopts="-forever "
   grep -q "^REMOTE_SHARED_SCREEN=TRUE" ${PCDMCONF}
   if [ $? -eq 0 ] ; then 
     vncopts="-shared "
   else
     vncopts="-nevershared "
   fi
   if [ -e "/usr/local/etc/vncpass" ] ; then
     vnccmd="x11vnc -display :0 $vncopts -passwdfile /usr/local/etc/vncpass -loop"
   else
     echo "WARNING: VNC enabled but no password in /usr/local/etc/vncpass!"
     sleep 5
   fi

fi


# Allow Auto-Login the first time PCDM starts
touch /tmp/.PCDMAutoLogin

# Clear out a failed marker
if [ -e "/tmp/.pcdm-x-failed" ] ; then
  rm /tmp/.pcdm-x-failed
fi

# Now start the X Server
while [ ! -e /var/run/nologin -a ! -e ${STOPFILE} ]; do
  /usr/local/bin/pc-checkxdisplay
  # Randomize the authorization file location
  PCDMAUTHFILE=${BASEPCDMAUTHFILE}-`openssl rand -hex 10`
  # Make sure the authorization file does not exist
  if [ -f ${PCDMAUTHFILE} ]; then
    rm ${PCDMAUTHFILE}
  fi
  export XAUTHORITY=${PCDMAUTHFILE} #Set the auth file location
  touch ${PCDMAUTHFILE} #Create the (empty) authorization file
  xauth -f ${PCDMAUTHFILE} add :0 MIT-MAGIC-COOKIE-1 `openssl rand -hex 64` #Add a default entry to the file (randomized)
  if [ -n "$vnccmd" ] ; then
    # Start VNC
    (sleep 10 ; $vnccmd >/var/log/vncserver 2>/var/log/vncserver) &
  fi

  # Remove our X success marker
  if [ -e "/tmp/.pcdm-x-started" ] ; then rm /tmp/.pcdm-x-started; fi

  xinit /usr/local/bin/PCDM-session -once -- :0 -auth ${PCDMAUTHFILE} $XOPTS
  if [ $? -ne 0 ] ; then
     if [ ! -e "/tmp/.pcdm-x-started" ] ; then
        # Looks like X failed to start...

        if [ -e "/tmp/.pcdm-x-failed" ] ; then
          # Wow, we really failed here, lets try running X wizard
          touch /var/.runxsetup
          rm /tmp/.pcdm-x-failed
        else
          # Lets move xorg.conf away, and try again
          touch /tmp/.pcdm-x-failed
          mv /etc/X11/xorg.conf /etc/X11/xorg.conf.prevFailed 2>/dev/null
        fi
     fi
  fi

  #Now remove the authorization file
  rm ${PCDMAUTHFILE}
done

#Remove the stopfile if it exists
rm ${STOPFILE}
