# New ports collection makefile for:	pcbsd-meta-kde-toys
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-kde-toys
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-kde-toys

RUN_DEPENDS=	kdetoys>=0:${PORTSDIR}/x11-clocks/kdetoys4

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
