#!/bin/sh
#        Name: mount_auto
#      Author: Tanner Schultz
#        Date: 12-16-05
#     License: Public domain
# Description: Throws a bunch of fstypes at it to see what sticks.
#              Currently supported filesystems are UFS, msdos, ntfs,
#              ext2, reiserfs, cd9660, udf
##########################################################################

mount -C UTF-8 -t ufs $@ 2> /dev/null || mount_msdosfs -C UTF-8 $@ 2> /dev/null || mount_ntfs -C UTF-8 -o ro $@ 2> /dev/null || mount_ext2fs -C UTF-8 $@ 2> /dev/null || mount_cd9660 -C UTF-8 $@ 2> /dev/null || mount_udf -C UTF-8 $@ 2> /dev/null || echo "mount: Insufficient permissions, unknown filesystem, or media not inserted" >&2
