#!/bin/sh
##################
#Setup the temporary program variables
program_name=%%PROGNAME%%;
program_path=%%PBIDIRPATH%%
#Perform the modification to /etc/rc.conf";
tmpfile=$(mktemp /tmp/.XXXXXX);
grep -v '${program_name}_' /etc/rc.conf > ${tmpfile}";
cat ${program_path}/etc/rc.conf >> ${tmpfile}";
mv ${tmpfile} /etc/rc.conf";