#############################################################################
# Makefile for building: pbi-manager
#############################################################################

PREFIX?= $(STAGEDIR)

####### Install

all:

install_doinstall:
	sh install.sh $(PREFIX)

install:  install_doinstall
