# New ports collection makefile for:	pcbsd-meta-rekonq
#
# $FreeBSD$
#

PORTNAME=	pcbsd-meta-rekonq
PORTVERSION=	CHGVERSION
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port pcbsd-meta-rekonq

RUN_DEPENDS=	rekonq>=0:${PORTSDIR}/www/rekonq

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
