#!/bin/sh 

# Source our functions
. /usr/local/share/pcbsd/scripts/functions.sh

# Set all our path variables
PATH="/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/bin:/usr/local/sbin"
export PATH

if [ -e "/root/.xprofile" ]
then
. /root/.xprofile
fi

# Setting a language
if [ -e "/etc/pcbsd-lang" ] ; then
   LANG=`cat /etc/pcbsd-lang`
   export LANG
fi
 
# We started up, let the backend script know
touch ${XGUITMP}/.xstartupsuccess

# Start our fluxbox WM
/usr/local/bin/startfluxbox &
PID=$!

# Ask user if they like the auto-detected resolution
/usr/local/bin/pc-xgui -firstprompt
if [ $? -eq 0 ] ; then
  # The user liked this res? Lets run the other stuff now
  touch ${XGUITMP}/.selected
  run_firstboot
  kill -9 ${PID}
  exit 0
fi

# The user wants to setup a manual resolution
/usr/local/bin/pc-xgui
if [ $? -ne 0 ] ; then
 echo "Canceled" > ${XGUITMP}/.canceled
fi
kill -9 ${PID}
